### ISSUE TITLE
Support NodeBB 0.6.x

### ISSUE THREAD

**Issue by Aure77** [frissdiegurke/nodebb-theme-dark-rectangles#6]
`"nodebb-theme-vanilla": "~0.0.91"` is outdated in package.json. Can you update / adpat this theme with lastest NobeBB version ?

**Comment by frissdiegurke** [comment]
I'll see if I can afford some time on this in the next weeks.
This project describes my first contact with bootstrap (learning by doing) and therefor the code-quality has much disadvantages...
Maybe I'll re-create a similar theme instead.
But first I have to find some spare time :clock11:

**Comment by frissdiegurke** [comment]
added support for now.
